"""Abstract base class for payoff definitions."""

from abc import ABC, abstractmethod
from collections.abc import Mapping

from numpy.typing import NDArray


class Payoff(ABC):
    """Base class for contingent claim payoffs.

    A payoff is a function of simulated paths that returns the discounted
    cashflow for each path. The engine handles discounting; the payoff
    returns undiscounted terminal or path-dependent cashflows.
    """

    @abstractmethod
    def cashflows(
        self,
        paths: NDArray,
        t_grid: NDArray,
        state_paths: Mapping[str, NDArray] | None = None,
    ) -> NDArray:
        """Compute the payoff for each simulated path.

        Parameters
        ----------
        paths : NDArray, shape (n_paths, n_steps+1)
            Simulated spot price paths.
        t_grid : NDArray, shape (n_steps+1,)
            Time grid corresponding to path columns.
        state_paths : mapping[str, NDArray] | None
            Optional full state path data generated by the dynamics.
            Includes at least `spot`, and may include extra states like
            `variance` for stochastic-volatility models.

        Returns
        -------
        NDArray, shape (n_paths,)
            Undiscounted payoff for each path.
        """

    @property
    @abstractmethod
    def expiry(self) -> float:
        """Time to expiry in years."""
